# imgpath is path to root of Silicosis V1 Dataset, and csvpath is the path to the related .csv
silicosis_857:
  imgpath: "/home/sean/MSc_2025/data/MBOD_Datasets/Dataset-2" # Path to V2 images
  csvpath: "/home/sean/MSc_2025/data/MBOD_Datasets/Dataset-2/Database_Training-2024.08.28.csv" # Path to V1 csv
  delimeter: ","
  image_id_column: "Anonymized Study Instance UID"
  radiologist_findings_columns:
    - "Radiologist: Findings"
  profusion_score_column: "MBOD Panel: Profusion"

# imgpath is path to root of Silicosis V2 Dataset, and csvpath is the path to the related .csv
silicosis_1179:
  imgpath: "/home/sean/MSc_2025/data/MBOD_Datasets/Dataset-1" # Path to V2 images
  csvpath: "/home/sean/MSc_2025/data/MBOD_Datasets/Dataset-1/CsvFileDatabaseWithRadiology.csv" # Path to V2 csv
  delimeter: ","
  image_id_column: "(0020,000d) UI Study Instance UID"
  profusion_score_column: "Profusion"
  radiologist_findings_columns:
    - "strFindingsSimplified1"
    - "strFindingsSimplified2"


ilo_refs:
  imgpath: "/home/sean/MSc_2025/data/ilo-radiographs-dicom"
  csvpath: "/home/sean/MSc_2025/data/ilo-radiographs-dicom/ilo-radiographs-dicom.csv"
  delimeter: ","
  image_id_column: "Image Name"
  profusion_score_column: "Profusion"
  radiologist_findings_columns: []

kaggle_TB:
  path: "" # Path to base directory of the Kaggle dataset
  outputpath: "/home/sean/MSc_2025/mbod-data-processor/kaggle_tb_dataset.h5"
  image_size: 512

merged_silicosis_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/mbod_dataset_merged_512.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to

mbod_857_silicosis_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/mbod_857_512.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to

mbod_1179_silicosis_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/mbod_1179_512.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to

ilo_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/ilo_dataset_512.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to

sz_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/sz_kaggle_dataset.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to
  
mc_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/mc_kaggle_dataset.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to


dataset_check: # Settings for verify and visualise
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/mbod_dataset_merged_512.h5"
  # label_scheme: "tuberculosis" # Label key to use (tuberculosis, silicosis, lab, etc.)
  label_scheme: "profusion_score" # Label key to use (tuberculosis, silicosis, lab, etc.)

