# imgpath is path to root of Silicosis V1 Dataset, and csvpath is the path to the related .csv
silicosis_857:
  imgpath: "/home/sean/MSc_2025/data/MBOD_Datasets/Dataset-2" # Path to V1 images
  csvpath: "/home/sean/MSc_2025/data/MBOD_Datasets/Dataset-2/Database_Training-2024.08.28.csv" # Path to V1 csv
  delimeter: ","
  image_id_column: "Anonymized Study Instance UID"
  radiologist_findings_columns:
    - "Radiologist: Findings"
  profusion_score_columns: 
    - "MBOD Panel: Profusion"
    - "Radiologist: ILO Profusion"

# imgpath is path to root of Silicosis V2 Dataset, and csvpath is the path to the related .csv
silicosis_1179:
  imgpath: "/home/sean/MSc_2025/data/MBOD_Datasets/Dataset-1" # Path to V2 images
  csvpath: "/home/sean/MSc_2025/data/MBOD_Datasets/Dataset-1/CsvFileDatabaseWithRadiology.csv" # Path to V2 csv
  delimeter: ","
  image_id_column: "(0020,000d) UI Study Instance UID"
  profusion_score_column: "Profusion"
  radiologist_findings_columns:
    - "strFindingsSimplified1"
    - "strFindingsSimplified2"


ilo_refs:
  imgpath: "/home/sean/MSc_2025/data/ilo-radiographs-dicom"
  csvpath: "/home/sean/MSc_2025/data/ilo-radiographs-dicom/ilo-radiographs-dicom.csv"
  delimeter: ","
  image_id_column: "Image Name"
  profusion_score_column: "Profusion"
  radiologist_findings_columns: []

kaggle_TB:
  path: "/home/sean/MSc_2025/data/TB_Chest_Radiography_Database" # Path to base directory of the Kaggle dataset
  outputpath: "/home/sean/MSc_2025/mbod-data-processor/kaggle_tb_dataset_mstb_new.h5"
  image_size: 512

merged_silicosis_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/mbod_512_mlabel_new.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to

mbod_857_silicosis_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/mbod_857_512_v3.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to

mbod_1179_silicosis_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/mbod_1179_512.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to

ilo_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/ilo_dataset_512.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to

shenzhen_tb:
  path: "/home/sean/MSc_2025/data/Shenzhen"
  outputpath: "/home/sean/MSc_2025/mbod-data-processor/shenzhen_tb_dataset.h5"

montgomery_tb:
  path: "/home/MSc_2025/data/Montgomery"
  outputpath: "/home/sean/MSc_2025/mbod-data-processor/montgomery_tb_dataset.h5"

merged_mc_sz_output:
  outputpath: "/home/sean/MSc_2025/mbod-data-processor/merged_mc_sz_output.h5"
  image_size: 512

sz_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/sz_kaggle_dataset.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to
  
mc_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/mc_kaggle_dataset.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to

rand_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/rand_v1_512.h5" # Path to read .hdf5 file from
  image_size: 512 # The size (height,width) the x-rays will be changed to

dataset_check: # Settings for verify and visualise
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/mbod_512_mlabel_new.h5" # Path to read .hdf5 file from
  # label_scheme: "tuberculosis" # Label key to use (tuberculosis, silicosis, lab, etc.)
  label_scheme: "silicosis" # Label key to use (tuberculosis, silicosis, lab, etc.)

MC_SZ_TB:
  path: "/home/sean/MSc_2025/data/mc-sz-combined"
  outputpath: "/home/sean/MSc_2025/mbod-data-processor/mc_sz_combined_512.h5"
  image_size: 512


combined_output:
  hdf5_file: "/home/sean/MSc_2025/mbod-data-processor/mbod_kaggle_combined.h5"  
  image_size: 512
