import itertools
from networks import init_net, define_D, define_G, ResnetGenerator, UnetGenerator, NLayerDiscriminator, init_weights
from helpers import init_weights


import torch
import torch.nn as nn

import sys
import os
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import torch
import numpy as np

class CycleGANModel(nn.Module):
    def __init__(self, input_nc, output_nc, ngf=64, ndf=64, netG='resnet_9blocks', netD='basic', n_layers_D=3,
                 norm='instance', init_type='normal', init_gain=0.02, device='cpu'):
        super(CycleGANModel, self).__init__()
        self.device = device

        # Define generators
        self.G_A = define_G(input_nc, output_nc, ngf, netG, norm, init_type, init_gain) # CAN ALSO USE DROPOUT 
        self.G_B = define_G(output_nc, input_nc, ngf, netG, norm, init_type, init_gain)

        # Define discriminators
        self.D_A = define_D(output_nc, ndf, netD, n_layers_D, norm, init_type, init_gain)
        self.D_B = define_D(input_nc, ndf, netD, n_layers_D, norm, init_type, init_gain)

        # Loss functions
        self.criterionGAN = nn.MSELoss().to(device)
        self.criterionCycle = nn.L1Loss().to(device)
        self.criterionIdt = nn.L1Loss().to(device)

        # Optimizers
        self.optimizer_G = torch.optim.Adam(itertools.chain(self.G_A.parameters(), self.G_B.parameters()), lr=0.0002, betas=(0.5, 0.999))
        self.optimizer_D_A = torch.optim.Adam(self.D_A.parameters(), lr=0.0002, betas=(0.5, 0.999))
        self.optimizer_D_B = torch.optim.Adam(self.D_B.parameters(), lr=0.0002, betas=(0.5, 0.999))


    def forward(self, real_A, real_B):
        self.fake_B = self.G_A(real_A)  # G_A(A)
        self.rec_A = self.G_B(self.fake_B)   # G_B(G_A(A))
        self.fake_A = self.G_B(real_B)  # G_B(B)
        self.rec_B = self.G_A(self.fake_A)   # G_A(G_B(B))

        return self.fake_A, self.fake_B, self.rec_A, self.rec_B
    
    def backward_D_basic(self, netD, real, fake):
            """Calculate GAN loss for the discriminator

            Parameters:
                netD (network)      -- the discriminator D
                real (tensor array) -- real images
                fake (tensor array) -- images generated by a generator

            Return the discriminator loss.
            We also call loss_D.backward() to calculate the gradients.
            """
            # Real
            pred_real = netD(real)
            loss_D_real = self.criterionGAN(pred_real, True)
            # Fake
            pred_fake = netD(fake.detach())
            loss_D_fake = self.criterionGAN(pred_fake, False)
            # Combined loss and calculate gradients
            loss_D = (loss_D_real + loss_D_fake) * 0.5
            loss_D.backward()
            return loss_D

    def backward_D_A(self):
        """Calculate GAN loss for discriminator D_A"""
        fake_B = self.fake_B_pool.query(self.fake_B)
        self.loss_D_A = self.backward_D_basic(self.D_A, self.real_B, fake_B)

    def backward_D_B(self):
        """Calculate GAN loss for discriminator D_B"""
        fake_A = self.fake_A_pool.query(self.fake_A)
        self.loss_D_B = self.backward_D_basic(self.D_B, self.real_A, fake_A)

    def backward_G(self):
        """Calculate the loss for generators G_A and G_B"""
        lambda_idt = self.opt.lambda_identity
        lambda_A = self.opt.lambda_A
        lambda_B = self.opt.lambda_B
        # Identity loss
        if lambda_idt > 0:
            # G_A should be identity if real_B is fed: ||G_A(B) - B||
            self.idt_A = self.netG_A(self.real_B)
            self.loss_idt_A = self.criterionIdt(self.idt_A, self.real_B) * lambda_B * lambda_idt
            # G_B should be identity if real_A is fed: ||G_B(A) - A||
            self.idt_B = self.netG_B(self.real_A)
            self.loss_idt_B = self.criterionIdt(self.idt_B, self.real_A) * lambda_A * lambda_idt
        else:
            self.loss_idt_A = 0
            self.loss_idt_B = 0

        # GAN loss D_A(G_A(A))
        self.loss_G_A = self.criterionGAN(self.netD_A(self.fake_B), True)
        # GAN loss D_B(G_B(B))
        self.loss_G_B = self.criterionGAN(self.netD_B(self.fake_A), True)
        # Forward cycle loss || G_B(G_A(A)) - A||
        self.loss_cycle_A = self.criterionCycle(self.rec_A, self.real_A) * lambda_A
        # Backward cycle loss || G_A(G_B(B)) - B||
        self.loss_cycle_B = self.criterionCycle(self.rec_B, self.real_B) * lambda_B
        # combined loss and calculate gradients
        self.loss_G = self.loss_G_A + self.loss_G_B + self.loss_cycle_A + self.loss_cycle_B + self.loss_idt_A + self.loss_idt_B
        self.loss_G.backward()
    
    def set_requires_grad(self, nets, requires_grad=False):
        """Set requies_grad=Fasle for all the networks to avoid unnecessary computations
        Parameters:
            nets (network list)   -- a list of networks
            requires_grad (bool)  -- whether the networks require gradients or not
        """
        if not isinstance(nets, list):
            nets = [nets]
        for net in nets:
            if net is not None:
                for param in net.parameters():
                    param.requires_grad = requires_grad

    def init_networks(self, init_type="normal", init_gain=0.02):
            """Initialize all networks: 1. move to device; 2. initialize weights

            Parameters:
                init_type (str) -- initialization method: normal | xavier | kaiming | orthogonal
                init_gain (float) -- scaling factor for normal, xavier and orthogonal
            """
            import os

            for name in self.model_names:
                if isinstance(name, str):
                    net = getattr(self, "net" + name)

                    # Move to device
                    if torch.cuda.is_available():
                        if "LOCAL_RANK" in os.environ:
                            local_rank = int(os.environ["LOCAL_RANK"])
                            net.to(local_rank)
                            print(f"Initialized network {name} with device cuda:{local_rank}")
                        else:
                            net.to(0)
                            print(f"Initialized network {name} with device cuda:0")
                    else:
                        net.to("cpu")
                        print(f"Initialized network {name} with device cpu")

                    # Initialize weights using networks function
                    init_weights(net, init_type, init_gain)